config/routes.rb
Squarefill::Application.routes.draw do
  resources :games

  get "pages/home"
  match '/result' => 'games#result' #for test view pages
  

  root :to => 'games#new'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :level, :size
  require "latinSquareGenerator"
  
  def generateSquare
      @temp = LatinSquareGenerator.Gen_covered_latin_square(self.size, mapLevelPercentage(self.level))
      return @temp
  end
  
  def mapLevelPercentage(level)
    return level*10
  end
  
  def checkSquare(inputSquare)
    return LatinSquareGenerator.Check_latin_square(inputSquare)
  end
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    @square = @game.generateSquare
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
  
  def result
    @game = Game.find(params[:id])
    
    puts '*************************' + params['cell00'.to_sym] + ' SIZE: ' + params[:size]
    @size = params[:size].to_i
    
    @inputsquare = Array.new(@size) { Array.new(@size){0} }
    
    @inputsquare.each_index do |row_i|
    	@inputsquare.each_index do |cell_i|
    	  @inputsquare[row_i][cell_i] = params[('cell' + row_i.to_s + cell_i.to_s).to_sym].to_i
    	end
    end  
     puts '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
    puts @inputsquare.inspect
    
    @answer = @game.checkSquare(@inputsquare)
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/_form.html.erb
<div id="insert-param">
  <%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.number_field :size, :placeholder => "Enter size of square", :min => 2, :max => 9 %> <br/> 
    <%= f.number_field :level, :placeholder => "Enter level of difficulty", :min => 2, :max => 5 %><br/>
    <div class="button"><%= f.submit "Start Game!" %></div>
  
<% end %>
</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Size</th>
    <th>Level</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.size %></td>
    <td><%= game.level %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<%= render 'layouts/header'%>
<%= render 'form' %>

app/views/games/result.html.erb
<%= render 'layouts/header'%>

<% if @answer == true %>
  <p id="result">Woohoo! You got all correct! <br />Wanna <%= link_to "play again", root_url %>?</p>
<% else %>
 <p id="result">Ooops :( You got mistakes. <br />Wanna <%= link_to "start a game", root_url %> again?</p>
<% end %>  

app/views/games/show.html.erb
<%= render 'layouts/header'%>

<p id="notice"><%#= notice %></p>

<%#= @game.size %><%#= @game.level %>

<div id="game">
  <%= form_tag result_path, :method => 'get' do %>
    <table class="square">
      <%= hidden_field_tag :size, @game.size %>
      <%= hidden_field_tag :id, @game.id %>
      
      <% @square.each_index do |row_i| %>
      <tr>
        <% @square.each_index do |cell_i| %>
            <% @tag = ('cell' + row_i.to_s + cell_i.to_s).to_sym %>
            <% if @square[row_i][cell_i] == 0 %>
              <td class="fill"><%= number_field_tag @tag, params[@tag], :min => 1, :max => @game.size %></td>
            <% else %>
              <td><%= @square[row_i][cell_i] %></td>
              <%= hidden_field_tag @tag, @square[row_i][cell_i] %>
            <% end %>
        <% end %>
      </tr>
      <% end %>
    </table>
    <div class="button"><%= submit_tag "Check", :name => nil %></div>

  <% end %>
</div>

<%#= link_to 'Edit', edit_game_path(@game) %>
<%#= link_to 'Back', games_path %>

app/views/layouts/_header.html.erb
<header>
	<h1>Square Fill</h1>
	<h2>a game of latin squares</h2>
</header>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= csrf_meta_tags %>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
  
  <title>Square Fill</title>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>

  <script type="text/javascript" src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script>
    <%= javascript_include_tag "application" %>

</head>
<body>
  <!--[if lt IE 8]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

  <div class="wrapper">
    <%= yield %>
  </div>
  
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>

  <script>$("h1").fitText(0.6);</script>
  
</body>
</html>

app/views/pages/home.html.erb
<h1>Square Fill</h1>
<p>A game of latin squares!</p>